project:
  type: book

book:
  title: "Hydroinformatics"
  author: "JP Gannon"
  date: "1/9/2024"
  chapters:
    - index.qmd
    - 01-Plotting_Demo_COMPLETE.qmd
    - 02-Programming_Basics_Demo_COMPLETE.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

